name: combine-sar
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - aom=3.9.1=h7bae524_0
  - backports.zstd=1.2.0=py310hdc7f11d_0
  - black=25.12.0=pyha5154f8_0
  - brotli-python=1.2.0=py310h6123dab_1
  - bullet-cpp=3.25=py310h25f4b65_5
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.10.19=py310hd8ed1ab_2
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=h3ff7a7c_1
  - double-conversion=3.3.1=h286801f_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - ffmpeg=8.0.0=gpl_h670d5b4_106
  - filelock=3.20.0=pyhd8ed1ab_0
  - flake8=7.3.0=pyhd8ed1ab_0
  - fmt=12.0.0=h669d743_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.44.4=h7542897_0
  - giflib=5.2.2=h93a5062_0
  - glslang=16.1.0=h60b4770_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py310h1b1a8f9_2
  - graphite2=1.3.14=hec049ff_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=haf38c7b_0
  - hdf5=1.14.6=nompi_hd3baa01_104
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - imath=3.2.2=h3470cca_0
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - jasper=4.2.8=hc0e5025_0
  - jinja2=3.1.6=pyhcf101f3_1
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libass=0.17.4=hcbd7ca7_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.11.0=4_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=4_hb0561ab_openblas
  - libclang-cpp19.1=19.1.7=default_h73dfc95_5
  - libclang13=21.1.7=default_h6e8f826_1
  - libcurl=8.17.0=hdece5d2_1
  - libcxx=21.1.7=hf598326_0
  - libde265=1.0.15=h2ffa867_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libglib=2.86.2=he69a767_0
  - libheif=1.19.7=gpl_h79e6334_100
  - libhwloc=2.12.1=default_ha3cc4f2_1003
  - libhwy=1.3.0=h48b13b8_1
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - libjxl=0.11.1=h3dcb153_5
  - liblapack=3.11.0=4_hd9741b5_openblas
  - liblapacke=3.11.0=4_h1b118fd_openblas
  - libllvm19=19.1.7=h8e0c9ce_2
  - libllvm21=21.1.7=h8e0c9ce_0
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopencv=4.12.0=qt6_py310h3b958df_609
  - libopenvino=2025.2.0=h56e7ac4_1
  - libopenvino-arm-cpu-plugin=2025.2.0=h56e7ac4_1
  - libopenvino-auto-batch-plugin=2025.2.0=he81eb65_1
  - libopenvino-auto-plugin=2025.2.0=he81eb65_1
  - libopenvino-hetero-plugin=2025.2.0=h273c05f_1
  - libopenvino-ir-frontend=2025.2.0=h273c05f_1
  - libopenvino-onnx-frontend=2025.2.0=h6386500_1
  - libopenvino-paddle-frontend=2025.2.0=h6386500_1
  - libopenvino-pytorch-frontend=2025.2.0=hec049ff_1
  - libopenvino-tensorflow-frontend=2025.2.0=hee62d61_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hec049ff_1
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.53=hfab5511_0
  - libpq=18.1=h944245b_2
  - libprotobuf=6.31.1=h658db43_2
  - librsvg=2.60.0=h5c55ec3_0
  - libsqlite=3.51.1=h9a5124b_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h4030677_1
  - libtorch=2.9.1=cpu_generic_h040b7fb_1
  - libusb=1.0.29=hbc156a2_0
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.7=h4a912ad_0
  - markupsafe=3.0.3=py310hf4fd40f_0
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - ncurses=6.5=h5e97a16_3
  - networkx=3.4.2=pyh267e887_2
  - nomkl=1.0=h5ca1d4c_0
  - numpy=2.2.6=py310h4d83441_0
  - opencv=4.12.0=qt6_py310hddd80d1_609
  - openexr=3.4.4=h3c4c831_0
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openjph=0.25.3=h23bdaea_0
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.0=h5503f6c_0
  - optree=0.18.0=py310h0e897d2_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.4=h875632e_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pcre2=10.46=h7125dd6_0
  - pillow=12.0.0=py310hce4cfee_2
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - pthread-stubs=0.4=hd74edd7_1002
  - pugixml=1.15=hd3d436d_0
  - py-opencv=4.12.0=qt6_py310hc8dcf69_609
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-abi=11=hc364b38_1
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pybullet=3.25=py310h0c8ef83_5
  - pycodestyle=2.14.0=pyhd8ed1ab_0
  - pyflakes=3.4.0=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.2=pyhcf101f3_0
  - python=3.10.19=hcd7f573_2_cpython
  - python_abi=3.10=8_cp310
  - pytokens=0.3.0=pyhcf101f3_0
  - pytorch=2.9.1=cpu_generic_py310_hd637c7a_1
  - pyyaml=6.0.3=py310hf4fd40f_0
  - qt6-main=6.9.3=hb266e41_0
  - rav1e=0.7.1=h0716509_3
  - readline=8.2=h1d1bf99_2
  - requests=2.32.5=pyhd8ed1ab_0
  - scipy=1.15.2=py310h32ab4ed_0
  - sdl2=2.32.56=h248ca61_0
  - sdl3=3.2.28=h919df07_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=h1a5098f_0
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hada39a4_1
  - spirv-tools=2025.4=ha7d2532_0
  - svt-av1=3.1.2=h12ba402_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=h66ce52b_1
  - tk=8.6.13=h892fb3f_3
  - tomli=2.3.0=pyhcf101f3_0
  - torchvision=0.24.1=cpu_py310_h875496e_0
  - torchvision-extra-decoders=0.0.2=py310hc96e667_5
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - urllib3=2.6.1=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libx11=1.8.12=h6a5fb8c_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xorg-libxext=1.3.6=hd74edd7_0
  - yaml=0.2.5=h925e9cb_3
  - zlib-ng=2.3.2=h248ca61_0
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - accelerate==1.12.0
      - cloudpickle==3.1.2
      - contourpy==1.3.2
      - control==0.10.2
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - fonttools==4.61.1
      - gym==0.26.2
      - gym-notices==0.1.0
      - gym-pybullet-drones==2.0.0
      - gymnasium==1.2.2
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - pandas==2.3.3
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - psutil==7.1.3
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - regex==2025.11.3
      - safetensors==0.7.0
      - sb3-contrib==2.7.1
      - six==1.17.0
      - stable-baselines3==2.7.1
      - tokenizers==0.22.1
      - transformers==4.57.3
      - transforms3d==0.4.2
      - tzdata==2025.2
      - ultralytics==8.3.237
      - ultralytics-thop==2.0.18
prefix: /Users/cadendinkel/miniconda3/envs/combine-sar
